name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.11'
          # mdbook-version: 'latest'

      - run: |
          cargo install mdbook-toc
          cd reachy_mobile_documentation/
          mdbook build -d ../docs
      - name: Deploy mdbook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RONOCO_TOKEN }}
          publish_dir: ./docs
